name: CI Checks - Feature Branches
on:
  push:
    branches:
      - 'feature/**'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'
      - name: grant executable status to gradlew
        run: chmod +x gradlew

      - name: Run commit tests
        run: ./gradlew test

      - name: Install Tree Utility
        run: sudo apt-get install tree

      - name: Show Full Build Directory Structure
        run: tree -L 4 build # Lists files 3 levels deep inside the build directory
      - name: Publish test report to PR
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/build/reports/xml/unit-tests/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}